[package]
name = "mytest"
version = "0.1.0"
authors = ["manitomanito"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
byteorder="1"
structopt="0.3.2"
sha1="0.6.0"
sha2="0.8.0"